use super::gl::GlContext;
use super::util::*;
use crate::platform::{OpenMode, PlatformOpenGl, PlatformWaker, PlatformWindow};
use crate::*;
use libc::c_ulong;
use raw_window_handle::RawWindowHandle;
use std::cell::{Cell, RefCell};
use std::collections::HashMap;
use std::ffi::{CStr, CString};
use std::mem::zeroed;
use std::os::unix::ffi::OsStrExt;
use std::panic::{AssertUnwindSafe, catch_unwind};
use std::ptr::null_mut;
use std::rc::Rc;
use std::sync::{Arc, RwLock};
use std::time::{Duration, Instant};
use x11::xinput2::{
    XI_Enter, XI_HierarchyChanged, XI_Motion, XIAllDevices, XIDeviceEvent, XIEventMask,
    XIMaskIsSet, XISelectEvents, XISetMask,
};
use x11::xlib::*;

/// The atom used for implementing [`PlatformWaker::wakeup`] and
/// [`WindowHandler::wakeup`].
///
/// It is implemented by sending a custom [`ClientMessage`] event to the window,
/// which will interrupt the wait immediately and get handled in
/// [`WindowImpl::handle_event`].
pub const ATOM_WAKEUP: &CStr = c"PICOVIEW_WAKEUP";

/// X11 implementation of [`PlatformWindow`].
pub struct WindowImpl {
    /// The X11 window ID.
    window_id: c_ulong,
    /// The X11 window parent ID.
    window_parent: Cell<c_ulong>,
    /// The X11 colormap for the window.
    ///
    /// Needs to be freed when the window is destroyed, otherwise it will leak.
    window_colormap: c_ulong,

    /// Reference to our X11 display connection.
    connection: Connection,
    /// [`PlatformWaker`] for this window, used to wake up the event loop from
    /// another thread.
    waker: Arc<WindowWakerImpl>,

    /// The refresh interval for the window, used to determine how often to call
    /// [`WindowHandler::frame`].
    refresh_interval: Duration,
    /// The DPI scale for the window, used as a hint for the client to scale the
    /// content of the window. Provided via [`PlatformWindow::scale`].
    dpi_scale: f64,

    /// Is the window closing? If true, the event loop will exit as soon as
    /// possible, and the window will be destroyed.
    is_closing: Cell<bool>,

    /// Is the window destroyed externally? If true, the window has been
    /// destroyed and should not be used/destroyed again.
    is_destroyed: Cell<bool>,

    /// Key modifiers state provided by the server, used to check for
    /// changes.
    key_modifiers: Cell<Modifiers>,
    /// Mouse cursor icon provided by our window, used to check for
    /// changes.
    cursor_icon: Cell<MouseCursor>,
    /// Mouse cursor position provided by the server, used to check for
    /// changes, `None` if the cursor is outside and not grabbed.
    cursor_position: Cell<Option<Point>>,
    /// Window position provided by the server or the window, used for restoring
    /// the window state on a call to [`PlatformWindow::set_visible`] among
    /// other things.
    window_position: Cell<Point>,
    /// Window size provided by the server, used to check for
    /// changes and for restoring the window state on a call to
    /// [`PlatformWindow::set_visible`] among other things.
    window_size: Cell<Size>,
    /// Window visibility state provided by the server, used to check for
    /// changes.
    window_visible: Cell<bool>,
    /// Window focus state provided by the server, used to check for
    /// changes.
    window_focused: Cell<bool>,
    /// Are we currently in the process of a drag and drop operation?
    dnd_dragging: Cell<bool>,
    /// Last gesture zoom level provided by the server, used for computing
    /// deltas.
    last_gesture_zoom: Cell<f64>,
    /// Last window position reported to the event handler, used to check for
    /// changes.
    last_window_position: Cell<Point>,
    /// Last window size reported to the event handler, used to check for
    /// changes.
    last_window_size: Cell<Size>,

    /// The current clipboard data, used to provide data to other
    /// applications.
    exchange_clipboard: RefCell<Exchange>,
    /// The current drag and drop data, used to provide data to other
    /// applications. TODO: currently not implemented, implement drag into other
    /// windows later.
    exchange_dragndrop: RefCell<Exchange>,

    /// Cache of X11 cursor IDs for each supported mouse cursor icon.
    cursor_cache: RefCell<HashMap<MouseCursor, X11Cursor>>,

    /// XInput2 extension info, `None` if not available. Used for high precision
    /// mouse events and gestures.
    xi2_info: Option<XI2Extension>,
    /// List of XInput2 device axes, used for computing scroll deltas.
    xi2_axes: RefCell<Vec<XI2DeviceAxis>>,

    /// Our window handler, this is what handles all window events generated by
    /// the server.
    handler: RefCell<Option<Box<dyn WindowHandler>>>,

    /// OpenGL context, or an error if the context could not be created.
    /// Used for [`PlatformWindow::opengl`].
    gl_context: Result<GlContext, OpenGlError>,
}

/// X11 implementation of [`PlatformWaker`].
pub struct WindowWakerImpl {
    window_id: c_ulong,
    display: RwLock<*mut Display>,
}

/// SAFETY: as we initialized X11 with XInitThreads, it is safe to access
/// [`Display`] concurrently.
unsafe impl Send for WindowWakerImpl {}
unsafe impl Sync for WindowWakerImpl {}

impl WindowImpl {
    pub unsafe fn open(
        options: WindowBuilder<'_>,
        mode: OpenMode,
    ) -> Result<WindowWaker, WindowError> {
        unsafe {
            match mode {
                OpenMode::Blocking => {
                    let window = Self::create(options, mode)?;
                    window.run_event_loop()?;
                    Ok(WindowWaker::default())
                }

                OpenMode::Embedded(..) | OpenMode::Transient(..) => {
                    // SAFETY: We promise below that the factory will not be
                    // used after we return by waiting until the window is created and the factory
                    // is used up.
                    let options =
                        std::mem::transmute::<WindowBuilder<'_>, WindowBuilder<'static>>(options);

                    let (sender, receiver) = std::sync::mpsc::sync_channel(0);

                    std::thread::spawn(move || {
                        match catch_unwind(AssertUnwindSafe(|| Self::create(options, mode))) {
                            // window opened ok
                            Ok(Ok(window)) => {
                                sender
                                    .send(Ok(Ok(window.waker())))
                                    .expect("failed to send window open result");
                                window.run_event_loop().ok();
                            }
                            // window failed to open
                            Ok(Err(err)) => {
                                sender
                                    .send(Ok(Err(err)))
                                    .expect("failed to send window open result");
                            }
                            // window factory panicked
                            Err(err) => {
                                sender
                                    .send(Err(err))
                                    .expect("failed to send window open result");
                            }
                        }
                    });

                    // NOTE: we wait here! this is important as we CANNOT return before the window
                    // is actually initialized, because: we need our error
                    // result, AND more importantly, we need to ensure that the factory (that can
                    // borrow from the outer scope) finishes initializing!!!! See the SAFETY comment
                    // above!
                    match receiver
                        .recv()
                        .expect("x11 window thread aborted before finishing opening the window")
                    {
                        Ok(Ok(waker)) => Ok(waker),
                        Ok(Err(err)) => Err(err),
                        Err(e) => std::panic::resume_unwind(e),
                    }
                }
            }
        }
    }

    unsafe fn create(options: WindowBuilder<'_>, mode: OpenMode) -> Result<Rc<Self>, WindowError> {
        unsafe {
            // open a new connection first
            let connection = Connection::open().ok_or_else(|| {
                WindowError::Platform("Failed to connect to X server".to_string())
            })?;

            let default_root = XDefaultRootWindow(connection.as_raw());
            let window_parent = match mode {
                OpenMode::Blocking => default_root,
                OpenMode::Embedded(RawWindowHandle::Xlib(handle)) => handle.window,
                OpenMode::Embedded(RawWindowHandle::Xcb(handle)) => handle.window.get() as u64,
                OpenMode::Transient(RawWindowHandle::Xlib(handle)) => handle.window,
                OpenMode::Transient(RawWindowHandle::Xcb(handle)) => handle.window.get() as u64,
                _ => return Err(WindowError::InvalidParent),
            };

            let visual_info = options
                .opengl
                .as_ref()
                .and_then(|config| {
                    // try to find the best config for the provided OpenGL config
                    GlContext::find_best_config(&connection, config, options.transparent)
                })
                .or_else(|| {
                    // try first our preferred config if an opengl one is unavailable
                    VisualConfig::try_new_true_color(
                        &connection,
                        if options.transparent { 32 } else { 24 },
                    )
                })
                .or_else(|| {
                    // fallback to a different config if our preferred one is not available
                    VisualConfig::try_new_true_color(
                        &connection,
                        if options.transparent { 24 } else { 32 },
                    )
                });

            // create a colormap with our config, needed for transparency, and for opengl
            // with some drivers (i think)
            let window_colormap = visual_info.as_ref().map_or(CopyFromParent as _, |visual| {
                XCreateColormap(
                    connection.as_raw(),
                    default_root,
                    visual.info().visual,
                    AllocNone,
                )
            });

            // finally, create our window
            let window_id = XCreateWindow(
                connection.as_raw(),
                match mode {
                    OpenMode::Embedded(..) => window_parent,
                    _ => default_root,
                },
                0,
                0,
                200,
                200,
                0,
                visual_info
                    .as_ref()
                    .map_or(CopyFromParent, |x| x.info().depth),
                InputOutput as u32,
                visual_info.as_ref().map_or(null_mut(), |x| x.info().visual),
                CWEventMask | CWColormap | CWBorderPixel,
                &mut XSetWindowAttributes {
                    border_pixel: 0,
                    colormap: window_colormap,
                    event_mask: ButtonPressMask
                        | ButtonReleaseMask
                        | StructureNotifyMask
                        | KeyPressMask
                        | KeyReleaseMask
                        | LeaveWindowMask
                        | PointerMotionMask
                        | FocusChangeMask
                        | ExposureMask,
                    ..zeroed()
                },
            );

            // failed to create a window, shouldnt happen, but just in case
            if window_id == 0 {
                if window_colormap != 0 {
                    XFreeColormap(connection.as_raw(), window_colormap);
                }

                // if we have an Xlib error, return that.
                connection.last_error().map_err(WindowError::Platform)?;

                // otherwise return a generic error
                return Err(WindowError::Platform(
                    "Failed to create X11 window".to_string(),
                ));
            }

            // transient hint (its not really a "parent" in the traditional sense)
            if let OpenMode::Transient(..) = mode {
                XSetTransientForHint(connection.as_raw(), window_id, window_parent);
            }

            // ask for close window messages
            XSetWMProtocols(
                connection.as_raw(),
                window_id,
                &mut connection.atom(c"WM_DELETE_WINDOW"),
                1,
            );

            // check if we have xinput2 available, and if so, select for events we want to
            // receive
            let (xi2_info, xi2_axes) = match XI2Extension::new(&connection) {
                Some(info) => {
                    let mut mask = [0; 4];
                    XISetMask(&mut mask, XI_Enter);
                    XISetMask(&mut mask, XI_Motion);
                    XISetMask(&mut mask, XI_HierarchyChanged);
                    XISetMask(&mut mask, XI_GesturePinchBegin);
                    XISetMask(&mut mask, XI_GesturePinchUpdate);
                    XISetMask(&mut mask, XI_GesturePinchEnd);
                    XISelectEvents(
                        connection.as_raw(),
                        window_id,
                        &mut XIEventMask {
                            deviceid: XIAllDevices,
                            mask_len: 4,
                            mask: mask.as_mut_ptr(),
                        },
                        1,
                    );

                    let axes = info.list_axes(&connection);
                    (Some(info), axes)
                }

                None => (None, Vec::new()),
            };

            // mark our window as drag and drop aware, so we can receive drag and drop
            // events from other applications
            {
                let data = [5u32];
                XChangeProperty(
                    connection.as_raw(),
                    window_id,
                    connection.atom(c"XdndAware"),
                    connection.atom(c"ATOM"),
                    32,
                    PropModeReplace,
                    data.as_ptr() as *mut _,
                    data.len() as _,
                );
            }

            // create our opengl context if we have a config provided
            let gl_context = options
                .opengl
                .map(|config| {
                    let Some(visual) = visual_info else {
                        return Err(OpenGlError::FormatUnsupported);
                    };

                    GlContext::new(connection.clone(), window_id as _, config, visual)
                })
                .unwrap_or_else(|| Err(OpenGlError::NotRequested));

            // get a refresh interval for our frame updates, default to 60hz if all else
            // fails
            let refresh_interval =
                Duration::from_secs_f64(1.0 / query_refresh_rate(&connection).unwrap_or(60.0));
            // get a dpi scale for our window, default to 96dpi (1.0)
            let dpi_scale = query_scale_dpi(&connection).unwrap_or(96.0) / 96.0;

            // if we get an error here, it means the window creation failed
            if let Err(e) = connection.last_error() {
                // cleanup so we dont leave a dangling window and colormap
                XDestroyWindow(connection.as_raw(), window_id);
                if window_colormap != 0 {
                    XFreeColormap(connection.as_raw(), window_colormap);
                }

                // :p
                return Err(WindowError::Platform(e));
            }

            // our window data, box it because [`WindowFactory`] requires a stable address
            // for the lifetime of the window. See [`run_event_loop`] for more details.
            let window = Rc::new(Self {
                waker: Arc::new(WindowWakerImpl {
                    display: RwLock::new(connection.as_raw()),
                    window_id,
                }),

                refresh_interval,
                dpi_scale,

                xi2_info,
                xi2_axes: RefCell::new(xi2_axes),

                is_closing: Cell::new(false),
                is_destroyed: Cell::new(false),

                cursor_icon: Cell::new(MouseCursor::Default),
                cursor_position: Cell::new(None),

                window_position: Cell::new(Point::default()),
                window_size: Cell::new(Size::default()),
                window_visible: Cell::new(false),
                window_focused: Cell::new(false),

                key_modifiers: Cell::new(Modifiers::default()),
                dnd_dragging: Cell::new(false),

                last_window_size: Cell::new(Size::default()),
                last_window_position: Cell::new(Point::default()),
                last_gesture_zoom: Cell::new(1.0),

                exchange_clipboard: RefCell::new(Exchange::Empty),
                exchange_dragndrop: RefCell::new(Exchange::Empty),

                handler: RefCell::new(None),

                window_id,
                window_parent: Cell::new(window_parent),
                window_colormap,

                gl_context,
                cursor_cache: RefCell::new(HashMap::new()),
                connection,
            });

            // SAFETY: we erase the lifetime of WindowImpl; it should be safe to do so
            // because:
            //  - because our window instance is rc'd, it has a stable address for the whole
            //    lifetime of the window
            //  - we manually dispose of our handler before WindowImpl gets dropped (see
            //    drop impl)
            let handler = match (options.factory)(Window(&*Rc::as_ptr(&window))) {
                Ok(handler) => handler,
                Err(error) => return Err(WindowError::Factory(error)),
            };

            // start accepting events
            window.handler.replace(Some(handler));

            // finally
            Ok(window)
        }
    }

    /// Poll the events until our window is closed.
    fn run_event_loop(self: Rc<Self>) -> Result<(), WindowError> {
        unsafe {
            // main loop
            // - use a fixed refresh interval to call into [`WindowHandler::frame`] at a
            //   consistent rate
            // - if an event happens, we will handle it immediately and continue waiting for
            //   the next event/until the frame timer runs out.
            let mut next_frame = Instant::now();

            // stop the loop if [`Window::close`] is called, or if the window is
            // destroyed externally
            while !self.is_closing.get() {
                let curr_frame = Instant::now();
                let wait_time = match next_frame.checked_duration_since(curr_frame) {
                    Some(wait_time) => wait_time,
                    None => {
                        self.with_handler(|e| e.frame());
                        next_frame = (next_frame + self.refresh_interval).max(curr_frame); //avoid death spiral by capping next_frame to the current time if we are behind schedule
                        next_frame.saturating_duration_since(curr_frame) // return the time until the next frame, or 0 if we are behind schedule
                    }
                };

                // flush any pending messages we could have
                XFlush(self.connection.as_raw());

                // check for errors if we have any
                self.connection
                    .async_last_error()
                    .map_err(WindowError::Platform)?;

                // wait until we get at least 1 event, or until the next frame timer runs out
                let num_events = wait_for_events(&self.connection, Some(wait_time))
                    .map_err(WindowError::Platform)?;

                // process events if we have any
                for _ in 0..num_events {
                    let mut event = XEvent { type_: 0 };

                    if XNextEvent(self.connection.as_raw(), &mut event) == 0 {
                        self.handle_event(event);

                        // if we get a DestroyNotify event, exit immediately
                        if self.is_destroyed.get() {
                            break;
                        }
                    }
                }
            }

            Ok(())
        }
    }

    /// Handle a single [`XEvent`] from the main event loop
    #[allow(non_upper_case_globals)]
    fn handle_event(&self, event: XEvent) {
        unsafe {
            match event.type_ {
                GenericEvent => {
                    let mut event = event.generic_event_cookie;

                    if let Some(xi2) = self.xi2_info.as_ref() {
                        xi2.query_event(&self.connection, &mut event, |event| {
                            match (*event).evtype {
                                XI_Motion => {
                                    let event = &*(event as *mut _ as *const XIDeviceEvent);

                                    let mask = std::slice::from_raw_parts(
                                        event.valuators.mask,
                                        event.valuators.mask_len as usize,
                                    );

                                    if event.sourceid == event.deviceid {
                                        self.handle_event_modifiers(keymask_to_mods(
                                            event.mods.effective as _,
                                        ));

                                        self.handle_event_motion(
                                            event.event_x,
                                            event.event_y,
                                            true,
                                        );

                                        let mut scroll_x = 0.0;
                                        let mut scroll_y = 0.0;

                                        let mut values = event.valuators.values;
                                        for i in 0..event.valuators.mask_len * 8 {
                                            if !XIMaskIsSet(mask, i) {
                                                continue;
                                            }

                                            let value = {
                                                let value = *values;
                                                values = values.offset(1);
                                                value
                                            };

                                            if let Some(axis) =
                                                self.xi2_axes.borrow_mut().iter_mut().find(|axis| {
                                                    axis.source_id == event.sourceid
                                                        && axis.valuator == i
                                                })
                                            {
                                                let delta = axis.track_position(value);
                                                match axis.kind {
                                                    XI2AxisKind::HorizontalScroll => {
                                                        scroll_x += delta
                                                    }
                                                    XI2AxisKind::VerticalScroll => {
                                                        scroll_y += delta
                                                    }
                                                }
                                            }
                                        }

                                        if scroll_x != 0.0 || scroll_y != 0.0 {
                                            self.with_handler(|e| {
                                                e.mouse_scroll(scroll_x, scroll_y)
                                            });
                                        }
                                    }
                                }

                                XI_Enter => {
                                    for device in self.xi2_axes.borrow_mut().iter_mut() {
                                        device.reset_position(&self.connection);
                                    }
                                }

                                XI_HierarchyChanged => {
                                    self.xi2_axes.replace(xi2.list_axes(&self.connection));
                                }

                                XI_GesturePinchBegin
                                | XI_GesturePinchUpdate
                                | XI_GesturePinchEnd => {
                                    let event = &*(event as *mut _ as *const XIGesturePinchEvent);

                                    if event.header.evtype == XI_GesturePinchBegin {
                                        self.last_gesture_zoom.set(1.0);
                                    }

                                    let new_zoom = event.scale;
                                    let old_zoom = self.last_gesture_zoom.replace(new_zoom);

                                    if new_zoom != old_zoom {
                                        self.with_handler(|e| e.gesture_zoom(new_zoom / old_zoom));
                                    }

                                    if event.delta_angle != 0.0 {
                                        self.with_handler(|e| e.gesture_rotate(event.delta_angle));
                                    }

                                    if event.delta_x != 0.0 || event.delta_y != 0.0 {
                                        self.with_handler(|e| {
                                            e.mouse_scroll(
                                                event.delta_x * 0.05,
                                                event.delta_y * 0.05,
                                            )
                                        });
                                    }
                                }

                                _ => {}
                            }
                        });
                    }
                }

                ClientMessage => {
                    let event = event.client_message;
                    if event.format == 32
                        && event.message_type == self.connection.atom(c"WM_PROTOCOLS") as _
                        && event.data.get_long(0) == self.connection.atom(c"WM_DELETE_WINDOW") as _
                    {
                        self.with_handler(|e| e.close_requested());
                    }

                    if event.format == 32
                        && event.message_type == self.connection.atom(ATOM_WAKEUP) as _
                    {
                        self.with_handler(|e| e.wakeup());
                    }

                    if event.format == 32
                        && event.message_type == self.connection.atom(c"XdndPosition") as _
                    {
                        let (x, y) = {
                            let packed = event.data.get_long(2);
                            ((packed >> 16) as u16 as i16, packed as u16 as i16)
                        };

                        let origin = self.window_position.get();
                        let point = Point {
                            x: x as f64 - origin.x,
                            y: y as f64 - origin.y,
                        };

                        let source = event.data.get_long(0) as c_ulong;
                        let effect = if !self.dnd_dragging.replace(true) {
                            let timestamp = event.data.get_long(3) as c_ulong;
                            let data = match parse_selection(
                                &self.connection,
                                self.window_id,
                                self.connection.atom(c"XdndSelection"),
                                self.connection.atom(c"XdndSelection"),
                                timestamp,
                            ) {
                                Ok(exchange) => exchange,
                                Err(SelectionError::Empty) => Exchange::Empty,
                                Err(SelectionError::Reentrant) => {
                                    self.exchange_dragndrop.borrow().clone()
                                }
                            };

                            self.with_handler(|e| e.drag_enter(data, point))
                                .unwrap_or(DropEffect::Reject)
                        } else {
                            self.with_handler(|e| e.drag_move(point))
                                .unwrap_or(DropEffect::Reject)
                        };

                        XSendEvent(
                            self.connection.as_raw(),
                            source,
                            0,
                            0,
                            &mut XEvent {
                                client_message: XClientMessageEvent {
                                    type_: ClientMessage,
                                    serial: 0,
                                    send_event: 1,
                                    display: self.connection.as_raw(),
                                    window: source,
                                    message_type: self.connection.atom(c"XdndStatus"),
                                    format: 32,
                                    data: {
                                        let mut data = ClientMessageData::default();
                                        data.set_long(0, self.window_id as _);
                                        data.set_long(
                                            1,
                                            if effect == DropEffect::Reject { 0 } else { 1 },
                                        ); // success

                                        data.set_long(2, 0); // no rectangle
                                        data.set_long(3, 0); // no rectangle
                                        data.set_long(
                                            4,
                                            encode_drop_effect(&self.connection, effect) as _,
                                        );

                                        data
                                    },
                                },
                            },
                        );

                        XFlush(self.connection.as_raw());
                    }

                    if event.format == 32
                        && event.message_type == self.connection.atom(c"XdndLeave") as _
                        && self.dnd_dragging.replace(false)
                    {
                        self.with_handler(|e| e.drag_leave());
                    }

                    if event.format == 32
                        && event.message_type == self.connection.atom(c"XdndDrop") as _
                        && self.dnd_dragging.replace(false)
                    {
                        let source = event.data.get_long(0) as c_ulong;
                        let effect = self
                            .with_handler(|e| e.drag_accept())
                            .unwrap_or(DropEffect::Reject);

                        XSendEvent(
                            self.connection.as_raw(),
                            source,
                            0,
                            0,
                            &mut XEvent {
                                client_message: XClientMessageEvent {
                                    type_: ClientMessage,
                                    serial: 0,
                                    send_event: 1,
                                    display: self.connection.as_raw(),
                                    window: source,
                                    message_type: self.connection.atom(c"XdndFinished"),
                                    format: 32,
                                    data: {
                                        let mut data = ClientMessageData::default();
                                        data.set_long(0, self.window_id as _);
                                        data.set_long(
                                            1,
                                            if effect == DropEffect::Reject { 0 } else { 1 },
                                        ); // success
                                        data.set_long(
                                            2,
                                            encode_drop_effect(&self.connection, effect) as _,
                                        );
                                        data
                                    },
                                },
                            },
                        );

                        XFlush(self.connection.as_raw());
                    }
                }

                DestroyNotify => {
                    self.is_closing.set(true);
                    self.is_destroyed.set(true);
                }

                ReparentNotify => {
                    let event = event.reparent;
                    self.window_parent.set(event.parent);
                }

                MapNotify => {
                    self.window_visible.set(true);
                    self.with_handler(|e| e.visibility_changed(WindowVisibility::Normal));
                }

                UnmapNotify => {
                    // TODO: add minimize check
                    self.window_visible.set(false);
                    self.with_handler(|e| e.visibility_changed(WindowVisibility::Hidden));
                }

                ConfigureNotify => {
                    let event = event.configure;
                    let size = Size {
                        width: event.width.try_into().unwrap_or(0),
                        height: event.height.try_into().unwrap_or(0),
                    };

                    if let Some(point) = window_position(&self.connection, self.window_id)
                        && self.last_window_position.replace(point) != point
                    {
                        self.window_position.set(point);
                        self.with_handler(|e| e.position_changed(point));
                    }

                    if self.last_window_size.replace(size) != size {
                        self.window_size.set(size);
                        self.with_handler(|e| e.size_changed(size));
                    }
                }

                ButtonPress | ButtonRelease => {
                    let event = event.button;

                    if event.type_ == ButtonPress {
                        XSetInputFocus(
                            self.connection.as_raw(),
                            self.window_id,
                            RevertToParent,
                            event.time,
                        );
                    }

                    self.handle_event_modifiers(keymask_to_mods(event.state));
                    self.handle_event_motion(event.x as f64, event.y as f64, false);

                    match event.button {
                        1 | 2 | 3 | 8 | 9 => {
                            let button = match event.button {
                                1 => MouseButton::Left,
                                2 => MouseButton::Middle,
                                3 => MouseButton::Right,
                                8 => MouseButton::Back,
                                9 => MouseButton::Forward,
                                _ => return,
                            };

                            self.with_handler(|e| {
                                e.mouse_press(button, event.type_ == ButtonPress)
                            });
                        }

                        4..=7 if event.type_ == ButtonPress && self.xi2_info.is_none() => {
                            let (x, y) = match event.button {
                                4 => (0.0, -1.0),
                                5 => (0.0, 1.0),
                                6 => (-1.0, 0.0),
                                7 => (1.0, 0.0),
                                _ => return,
                            };

                            self.with_handler(|e| e.mouse_scroll(x, y));
                        }

                        _ => {}
                    };
                }

                KeyPress | KeyRelease => {
                    let event = event.key;

                    self.handle_event_modifiers(keymask_to_mods(event.state));

                    // ignore auto-repeat release events, autorepeats will be reported as repeated
                    // KeyPress events without corresponding KeyRelease events
                    if is_autorepeat_release(&self.connection, &event) {
                        return;
                    }

                    if let Some(key) = keycode_to_key(event.keycode) {
                        let capture = self
                            .with_handler(|e| e.key_press(key, event.type_ == KeyPress))
                            .unwrap_or(false);

                        if !capture {
                            XSendEvent(
                                self.connection.as_raw(),
                                self.window_parent.get(),
                                1,
                                match event.type_ {
                                    KeyPress => KeyPressMask,
                                    _ => KeyReleaseMask,
                                },
                                &mut XEvent {
                                    key: XKeyEvent {
                                        window: self.window_parent.get(),
                                        ..event
                                    },
                                },
                            );
                        }
                    }
                }

                MotionNotify => {
                    let event = event.motion;
                    self.handle_event_modifiers(keymask_to_mods(event.state));
                    self.handle_event_motion(event.x as f64, event.y as f64, false);
                }

                LeaveNotify => {
                    let event = event.crossing;
                    self.handle_event_modifiers(keymask_to_mods(event.state));

                    const ANY_BUTTON: u32 =
                        Button1Mask | Button2Mask | Button3Mask | Button4Mask | Button5Mask;

                    let grabbed = (event.state & ANY_BUTTON) != 0;
                    if grabbed || self.cursor_position.replace(None).is_none() {
                        return;
                    }

                    self.with_handler(|e| e.mouse_leave());
                }

                FocusIn | FocusOut => {
                    let event = event.focus_change;
                    let focus = event.type_ == FocusIn;

                    if event.mode != NotifyNormal || event.window != self.window_id {
                        return;
                    }

                    if self.window_focused.replace(focus) != focus {
                        self.with_handler(|e| e.focus_changed(focus));
                    }
                }

                Expose => {
                    let event = event.expose;
                    self.with_handler(|e| {
                        e.damage(Rect::from_xywh(
                            event.x,
                            event.y,
                            event.width.try_into().unwrap_or(0),
                            event.height.try_into().unwrap_or(0),
                        ))
                    });
                }

                SelectionRequest => {
                    let mut event = event.selection_request;
                    let exchange = &*self.exchange_clipboard.borrow();

                    if event.selection != self.connection.atom(c"CLIPBOARD") {
                        return;
                    }

                    let a_targets = self.connection.atom(c"TARGETS");
                    let a_utf8_string = self.connection.atom(c"UTF8_STRING");
                    let a_text_plain = self.connection.atom(c"text/plain");
                    let a_text_uri_list = self.connection.atom(c"text/uri-list");

                    if event.property != 0 && event.target == a_targets {
                        let atom = match exchange {
                            Exchange::Files(_) => a_text_uri_list,
                            Exchange::Empty | Exchange::Text(_) => a_utf8_string,
                        };

                        XChangeProperty(
                            self.connection.as_raw(),
                            event.requestor,
                            event.property,
                            XA_ATOM,
                            32,
                            PropModeReplace,
                            &atom as *const _ as *const u8,
                            1,
                        );
                    } else if event.property != 0
                        && (event.target == a_utf8_string
                            || event.target == a_text_plain
                            || event.target == XA_STRING)
                        && let Exchange::Text(text) = exchange
                    {
                        XChangeProperty(
                            self.connection.as_raw(),
                            event.requestor,
                            event.property,
                            event.target,
                            8,
                            PropModeReplace,
                            text.as_ptr(),
                            text.len() as i32,
                        );
                    } else if event.property != 0
                        && event.target == a_text_uri_list
                        && let Exchange::Files(files) = exchange
                    {
                        let list = encode_uri_list(files);
                        XChangeProperty(
                            self.connection.as_raw(),
                            event.requestor,
                            event.property,
                            event.target,
                            8,
                            PropModeReplace,
                            list.as_bytes().as_ptr(),
                            list.len() as i32,
                        );
                    } else {
                        // wasnt accepted, send a SelectionNotify with property set to None
                        event.property = 0;
                    };

                    XSendEvent(
                        self.connection.as_raw(),
                        event.requestor,
                        0,
                        NoEventMask,
                        &mut XEvent {
                            selection: x11::xlib::XSelectionEvent {
                                type_: SelectionNotify,
                                serial: 0,
                                send_event: 1,
                                display: event.display,
                                requestor: event.requestor,
                                selection: event.selection,
                                target: event.target,
                                property: event.property,
                                time: event.time,
                            },
                        },
                    );

                    // just in case
                    XFlush(self.connection.as_raw());
                }

                _ => {}
            }
        }
    }

    /// Emits a [`WindowHandler::mouse_move`] event if the cursor position has
    /// changed.
    fn handle_event_motion(&self, x: f64, y: f64, is_precise: bool) {
        // if we have xinput2 and this is a xi1 event...
        if !is_precise && self.xi2_info.is_some() {
            // we should ignore it as xinput2 will provide us with a better precision
            // event...

            let size = self.window_size.get();
            if x >= 0.0 && y >= 0.0 && x <= size.width as f64 && y <= size.height as f64 {
                // unless it is out of bounds, as xinput2 will not provide us
                // with out of bound events
                return;
            }
        }

        let point = Point { x, y };
        if self.cursor_position.replace(Some(point)) != Some(point) {
            self.with_handler(|e| e.mouse_move(point)); // TODO: absolute?
        }
    }

    /// Emits a [`WindowHandler::key_modifiers`] event if the modifiers have
    /// changed.
    fn handle_event_modifiers(&self, modifiers: Modifiers) {
        if self.key_modifiers.replace(modifiers) != modifiers {
            self.with_handler(|e| e.key_modifiers(modifiers));
        }
    }

    /// Access the [`WindowHandler`] if available.
    fn with_handler<R>(&self, f: impl FnOnce(&mut dyn WindowHandler) -> R) -> Option<R> {
        (*self.handler.borrow_mut())
            .as_mut()
            .map(|handler| f(handler.as_mut()))
    }
}

impl Drop for WindowImpl {
    fn drop(&mut self) {
        // we set waker display to null before sending the close event, to ensure that
        // any pending wakeups that get triggered by the close event will be
        // ignored, preventing a potential use-after-free in the
        // `WindowWakerImpl::wakeup` method
        if let Ok(mut display) = self.waker.display.write() {
            *display = std::ptr::null_mut();
        }

        // handler MUST be dropped BEFORE `WindowImpl` gets dropped, as handler depends
        // on WindowImpl. See safety comment in [`WindowImpl::set_event_handler`] for
        // more details.
        self.handler.take();

        unsafe {
            // kill the window itself
            if !self.is_destroyed.get() {
                XDestroyWindow(self.connection.as_raw(), self.window_id);
            }

            // free our colormap
            if self.window_colormap != 0 {
                XFreeColormap(self.connection.as_raw(), self.window_colormap);
            }

            // sync
            XSync(self.connection.as_raw(), 0);
        }
    }
}

impl PlatformWindow for WindowImpl {
    fn window_handle(&self) -> rwh_06::RawWindowHandle {
        rwh_06::RawWindowHandle::Xlib(rwh_06::XlibWindowHandle::new(self.window_id))
    }

    fn display_handle(&self) -> rwh_06::RawDisplayHandle {
        rwh_06::RawDisplayHandle::Xlib(self.connection.display_handle())
    }

    fn close(&self) {
        self.is_closing.set(true);
    }

    fn waker(&self) -> WindowWaker {
        WindowWaker(self.waker.clone())
    }

    fn opengl(&self) -> Result<&dyn PlatformOpenGl, OpenGlError> {
        match &self.gl_context {
            Ok(gl) => Ok(gl),
            Err(e) => Err(e.clone()),
        }
    }

    fn scale(&self) -> f64 {
        self.dpi_scale
    }

    fn set_title(&self, title: &str) {
        if let Ok(title) = CString::new(title.to_owned()) {
            unsafe {
                let mut text = XTextProperty { ..zeroed() };
                let status =
                    XStringListToTextProperty(&mut (title.as_ptr() as *mut _), 1, &mut text);
                if status != 0 {
                    XSetWMName(self.connection.as_raw(), self.window_id, &mut text);
                    XFree(text.value as *mut _);
                }
            }
        }
    }

    fn set_decorations(&self, decorations: bool) {
        // _NET_WM_WINDOW_TYPE
        unsafe {
            let data: [u32; 1] = [match decorations {
                true => self.connection.atom(c"_NET_WM_WINDOW_TYPE_NORMAL") as u32,
                false => self.connection.atom(c"_NET_WM_WINDOW_TYPE_DOCK") as u32,
            }];

            XChangeProperty(
                self.connection.as_raw(),
                self.window_id,
                self.connection.atom(c"_NET_WM_WINDOW_TYPE"),
                self.connection.atom(c"ATOM"),
                32,
                PropModeReplace,
                data.as_ptr() as *mut _,
                data.len() as _,
            );
        }

        // _MOTIF_WM_HINTS
        unsafe {
            let data: [u32; 5] = [
                0b10,
                0,
                match decorations {
                    true => 1,
                    false => 0,
                },
                0,
                0,
            ];

            XChangeProperty(
                self.connection.as_raw(),
                self.window_id,
                self.connection.atom(c"_MOTIF_WM_HINTS"),
                self.connection.atom(c"ATOM"),
                32,
                PropModeReplace,
                data.as_ptr() as *mut _,
                data.len() as _,
            );
        }

        // re-map the window to apply the changes
        if self.window_visible.get() {
            self.set_visible(false);
            self.set_visible(true);
        }
    }

    fn set_cursor_icon(&self, cursor: MouseCursor) {
        // if the cursor is the same as the last one, we don't need to change it
        //
        // needed because of a promise we made that it is safe to call this every frame
        // (see [`Window::set_cursor_icon`])
        if self.cursor_icon.replace(cursor) == cursor {
            return;
        }

        unsafe {
            let cursor = self
                .cursor_cache
                .borrow_mut()
                .entry(cursor)
                .or_insert_with(|| {
                    X11Cursor::load(self.connection.clone(), cursor).unwrap_or_else(|| {
                        X11Cursor::load(self.connection.clone(), MouseCursor::Default)
                            .unwrap_or_else(|| X11Cursor::empty(self.connection.clone()))
                    })
                })
                .as_raw();

            XChangeWindowAttributes(
                self.connection.as_raw(),
                self.window_id,
                CWCursor,
                &mut XSetWindowAttributes { cursor, ..zeroed() },
            );
        }
    }

    fn set_cursor_position(&self, point: Point) {
        unsafe {
            XWarpPointer(
                self.connection.as_raw(),
                0,
                self.window_id,
                0,
                0,
                0,
                0,
                point.x.round() as i32,
                point.y.round() as i32,
            );
        }
    }

    fn set_size(&self, size: Size) {
        if self.window_size.replace(size) == size {
            return;
        }

        let (width, height) = (
            size.width.try_into().unwrap_or(i32::MAX),
            size.height.try_into().unwrap_or(i32::MAX),
        );

        unsafe {
            XConfigureWindow(
                self.connection.as_raw(),
                self.window_id,
                (CWWidth | CWHeight) as _,
                &mut XWindowChanges {
                    width,
                    height,
                    ..zeroed()
                },
            );
        }
    }

    fn set_min_size(&self, size: Size) {
        let (min_width, min_height) = (
            size.width.try_into().unwrap_or(i32::MAX),
            size.height.try_into().unwrap_or(i32::MAX),
        );

        unsafe {
            let mut hints = XSizeHints { ..zeroed() };

            XGetWMNormalHints(self.connection.as_raw(), self.window_id, &mut hints, &mut 0);

            hints.flags |= PMinSize;
            hints.min_width = min_width;
            hints.min_height = min_height;

            XSetWMNormalHints(self.connection.as_raw(), self.window_id, &mut hints);
        }
    }

    fn set_max_size(&self, size: Size) {
        let (max_width, max_height) = (
            size.width.try_into().unwrap_or(i32::MAX),
            size.height.try_into().unwrap_or(i32::MAX),
        );

        unsafe {
            let mut hints = XSizeHints { ..zeroed() };

            XGetWMNormalHints(self.connection.as_raw(), self.window_id, &mut hints, &mut 0);

            hints.flags |= PMaxSize;
            hints.max_width = max_width;
            hints.max_height = max_height;

            XSetWMNormalHints(self.connection.as_raw(), self.window_id, &mut hints);
        }
    }

    fn set_position(&self, point: Point) {
        if self.window_position.replace(point) == point {
            return;
        }

        unsafe {
            XConfigureWindow(
                self.connection.as_raw(),
                self.window_id,
                (CWX | CWY) as _,
                &mut XWindowChanges {
                    x: point.x as i32,
                    y: point.y as i32,
                    ..zeroed()
                },
            );
        }
    }

    fn set_visible(&self, visible: bool) {
        if self.window_visible.replace(visible) == visible {
            return;
        }

        unsafe {
            if visible {
                let size = self.window_size.get();
                let point = self.window_position.get();

                XMapRaised(self.connection.as_raw(), self.window_id);

                // TODO: fix positioning (client area vs border area)
                if size.width > 0 && size.height > 0 {
                    XConfigureWindow(
                        self.connection.as_raw(),
                        self.window_id,
                        (CWX | CWY | CWWidth | CWHeight) as _,
                        &mut XWindowChanges {
                            x: point.x as i32,
                            y: point.y as i32,
                            width: size.width.try_into().unwrap_or(i32::MAX),
                            height: size.height.try_into().unwrap_or(i32::MAX),
                            ..zeroed()
                        },
                    );
                }

                XSync(self.connection.as_raw(), 0);
            } else {
                XUnmapWindow(self.connection.as_raw(), self.window_id);
                XSync(self.connection.as_raw(), 0);
            }
        }
    }

    fn open_url(&self, url: &str) -> bool {
        open_url(url)
    }

    fn get_clipboard(&self) -> Exchange {
        let a_clipboard = self.connection.atom(c"CLIPBOARD");
        let a_xsel_data = self.connection.atom(c"XSEL_DATA");

        match parse_selection(
            &self.connection,
            self.window_id,
            a_clipboard,
            a_xsel_data,
            CurrentTime,
        ) {
            Ok(exchange) => exchange,
            Err(SelectionError::Empty) => Exchange::Empty,
            Err(SelectionError::Reentrant) => self.exchange_clipboard.borrow().clone(),
        }
    }

    fn set_clipboard(&self, data: Exchange) -> bool {
        let is_empty = matches!(data, Exchange::Empty);

        *self.exchange_clipboard.borrow_mut() = data;

        unsafe {
            XSetSelectionOwner(
                self.connection.as_raw(),
                self.connection.atom(c"CLIPBOARD"),
                if is_empty { 0 } else { self.window_id },
                CurrentTime,
            );
        }

        true
    }
}

impl PlatformWaker for WindowWakerImpl {
    fn wakeup(&self) -> Result<(), WakeupError> {
        let display = self.display.read().map_err(|_| WakeupError)?;

        if display.is_null() {
            return Err(WakeupError);
        }

        unsafe {
            XSendEvent(
                *display,
                self.window_id,
                1,
                NoEventMask,
                &mut XEvent {
                    client_message: XClientMessageEvent {
                        type_: ClientMessage,
                        serial: 0,
                        send_event: 1,
                        display: *display,
                        window: self.window_id,
                        message_type: XInternAtom(*display, ATOM_WAKEUP.as_ptr(), 0),
                        format: 32,
                        data: ClientMessageData::new(),
                    },
                },
            );
            XFlush(*display);
        }

        Ok(())
    }
}
